#!/bin/bash

sudo rsync -aq ./lib /usr/local/macos-web-development/

sudo rsync -aq ./httpd-vhosts.conf /usr/local/macos-web-development/
sudo rsync -aq ./LICENSE.txt /usr/local/macos-web-development/
sudo rsync -aq ./macos-web-development.sh /usr/local/macos-web-development/
sudo rsync -aq ./php.ini /usr/local/macos-web-development/
sudo rsync -aq ./README.md /usr/local/macos-web-development/
sudo rsync -aq ./sphp.sh /usr/local/macos-web-development/

if ! [ -d /usr/local/bin ]; then
    sudo mkdir /usr/local/bin
fi

if ! [ -L /usr/local/bin/macos-web-development ]; then
    sudo ln -s /usr/local/macos-web-development/macos-web-development.sh /usr/local/bin/macos-web-development
fi
