#!/bin/bash

# ----------------------------------------------------------
# Print help
# ----------------------------------------------------------

print_help ()
{
    echo ""
    echo -e "${C_1}Installs MacOS web development stuff:${C_0}"
    echo -e "${C_EM} • xcode-select (Xcode command line developer tools)${C_0}"
    echo -e "${C_EM} • Homebrew${C_0}"
    echo -e "${C_EM} • Openldap${C_0}"
    echo -e "${C_EM} • Libiconv${C_0}"
    echo -e "${C_EM} • MySQL${C_0}"
    echo -e "${C_EM} • Dnsmasq${C_0}"
    echo -e "${C_EM} • Apache (via Homebrew)${C_0}"
    echo -e "${C_EM} • PHP versions 5.6 to 7.4 (optional)${C_0}"
    echo -e "${C_EM} • sphp – a PHP switcher script${C_0}"
    echo ""
    echo -e "${C_1}By default ${C_EM}macos-web-development${C_1} performs a dry run and installs nothing. Use ${C_INFO}--no-dry-run${C_1} to actually do stuff.${C_0}"
    echo ""
    echo -e "${C_1}After installation you can run ${C_0}sphp 8.1${C_1} to switch PHP version (use desired version). ${C_0}sphp${C_1} only works with Apache from Homebrew.${C_0}"
    echo ""
    echo -e "${C_1}Options:${C_0}"
    echo -e "${C_INFO}-h, --help            ${C_EM}Display this help${C_0}"
    echo -e "${C_INFO}--no-apache           ${C_EM}Skip Apache${C_0}"
    echo -e "${C_INFO}--no-dnsmasq          ${C_EM}Skip Dnsmasq${C_0}"
    echo -e "${C_INFO}--no-dry-run          ${C_EM}Disable dry run and actually install stuff${C_0}"
    echo -e "${C_INFO}--no-mysql            ${C_EM}Skip MySQL${C_0}"
    echo -e "${C_INFO}--no-php              ${C_EM}Skip PHP${C_0}"
    echo -e "${C_INFO}--no-php-5-6          ${C_EM}Skip PHP 5.6${C_0}"
    echo -e "${C_INFO}--no-php-7-0          ${C_EM}Skip PHP 7.0${C_0}"
    echo -e "${C_INFO}--no-php-7-1          ${C_EM}Skip PHP 7.1${C_0}"
    echo -e "${C_INFO}--no-php-7-2          ${C_EM}Skip PHP 7.2${C_0}"
    echo -e "${C_INFO}--no-php-7-3          ${C_EM}Skip PHP 7.3${C_0}"
    echo -e "${C_INFO}--no-php-7-4          ${C_EM}Skip PHP 7.4${C_0}"
    echo -e "${C_INFO}--no-php-8-0          ${C_EM}Skip PHP 8.0${C_0}"
    echo -e "${C_INFO}--no-php-8-1          ${C_EM}Skip PHP 8.1${C_0}"
    echo -e "${C_INFO}--no-php-enable       ${C_EM}Will not enable the latest PHP version installed${C_0}"
    echo -e "${C_INFO}--no-xcode-select     ${C_EM}Skip xcode-select${C_0}"
    echo -e "${C_INFO}--only-apache         ${C_EM}Only install Apache${C_0}"
    echo -e "${C_INFO}--only-dnsmasq        ${C_EM}Only install Dnsmasq${C_0}"
    echo -e "${C_INFO}--only-mysql          ${C_EM}Only install MySQL${C_0}"
    echo -e "${C_INFO}--only-php            ${C_EM}Only install PHP${C_0}"
    echo -e "${C_INFO}--only-php-5-6        ${C_EM}Only install PHP 5.6. Combine with --only-php if desired${C_0}"
    echo -e "${C_INFO}--only-php-7-0        ${C_EM}Only install PHP 7.0. Combine with --only-php if desired${C_0}"
    echo -e "${C_INFO}--only-php-7-1        ${C_EM}Only install PHP 7.1. Combine with --only-php if desired${C_0}"
    echo -e "${C_INFO}--only-php-7-2        ${C_EM}Only install PHP 7.2. Combine with --only-php if desired${C_0}"
    echo -e "${C_INFO}--only-php-7-3        ${C_EM}Only install PHP 7.3. Combine with --only-php if desired${C_0}"
    echo -e "${C_INFO}--only-php-7-4        ${C_EM}Only install PHP 7.4. Combine with --only-php if desired${C_0}"
    echo -e "${C_INFO}--only-php-8-0        ${C_EM}Only install PHP 8.0. Combine with --only-php if desired${C_0}"
    echo -e "${C_INFO}--only-php-8-1        ${C_EM}Only install PHP 8.1. Combine with --only-php if desired${C_0}"
    echo -e "${C_INFO}--only-xcode-select   ${C_EM}Only install xcode-select${C_0}"
    echo -e "${C_INFO}--p-common            ${C_EM}Sets options ${C_0}--only-php-7-4 --no-xcode-select"
    echo -e "${C_INFO}--p-minimal           ${C_EM}Sets options ${C_0}--no-mysql --only-php-7-4 --no-xcode-select"
    echo -e "${C_INFO}--uninstall           ${C_EM}Uninstall stuff, but leave some stuff${C_0}"
    echo ""
}
